# Generated by Django 3.1.7 on 2021-03-17 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_auto_20210317_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorive',
            new_name='Favorite',
        ),
    ]
